# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/network/rate_limit/v2/rate_limit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.api.v2.ratelimit import ratelimit_pb2 as envoy_dot_api_dot_v2_dot_ratelimit_dot_ratelimit__pb2
from envoy.config.ratelimit.v2 import rls_pb2 as envoy_dot_config_dot_ratelimit_dot_v2_dot_rls__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from validate import validate_pb2 as validate_dot_validate__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/network/rate_limit/v2/rate_limit.proto',
  package='envoy.config.filter.network.rate_limit.v2',
  syntax='proto3',
  serialized_pb=_b('\n:envoy/config/filter/network/rate_limit/v2/rate_limit.proto\x12)envoy.config.filter.network.rate_limit.v2\x1a&envoy/api/v2/ratelimit/ratelimit.proto\x1a#envoy/config/ratelimit/v2/rls.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\x1a\x14gogoproto/gogo.proto\"\xb0\x02\n\tRateLimit\x12\x1e\n\x0bstat_prefix\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\x19\n\x06\x64omain\x18\x02 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12L\n\x0b\x64\x65scriptors\x18\x03 \x03(\x0b\x32+.envoy.api.v2.ratelimit.RateLimitDescriptorB\n\xba\xe9\xc0\x03\x05\x92\x01\x02\x08\x01\x12\x30\n\x07timeout\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationB\x04\x98\xdf\x1f\x01\x12\x19\n\x11\x66\x61ilure_mode_deny\x18\x05 \x01(\x08\x12M\n\x12rate_limit_service\x18\x06 \x01(\x0b\x32\x31.envoy.config.ratelimit.v2.RateLimitServiceConfigBO\n7io.envoyproxy.envoy.config.filter.network.rate_limit.v2B\x0eRateLimitProtoP\x01Z\x02v2b\x06proto3')
  ,
  dependencies=[envoy_dot_api_dot_v2_dot_ratelimit_dot_ratelimit__pb2.DESCRIPTOR,envoy_dot_config_dot_ratelimit_dot_v2_dot_rls__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_RATELIMIT = _descriptor.Descriptor(
  name='RateLimit',
  full_name='envoy.config.filter.network.rate_limit.v2.RateLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat_prefix', full_name='envoy.config.filter.network.rate_limit.v2.RateLimit.stat_prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='domain', full_name='envoy.config.filter.network.rate_limit.v2.RateLimit.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='descriptors', full_name='envoy.config.filter.network.rate_limit.v2.RateLimit.descriptors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\222\001\002\010\001'))),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='envoy.config.filter.network.rate_limit.v2.RateLimit.timeout', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\230\337\037\001'))),
    _descriptor.FieldDescriptor(
      name='failure_mode_deny', full_name='envoy.config.filter.network.rate_limit.v2.RateLimit.failure_mode_deny', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate_limit_service', full_name='envoy.config.filter.network.rate_limit.v2.RateLimit.rate_limit_service', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=566,
)

_RATELIMIT.fields_by_name['descriptors'].message_type = envoy_dot_api_dot_v2_dot_ratelimit_dot_ratelimit__pb2._RATELIMITDESCRIPTOR
_RATELIMIT.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_RATELIMIT.fields_by_name['rate_limit_service'].message_type = envoy_dot_config_dot_ratelimit_dot_v2_dot_rls__pb2._RATELIMITSERVICECONFIG
DESCRIPTOR.message_types_by_name['RateLimit'] = _RATELIMIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RateLimit = _reflection.GeneratedProtocolMessageType('RateLimit', (_message.Message,), dict(
  DESCRIPTOR = _RATELIMIT,
  __module__ = 'envoy.config.filter.network.rate_limit.v2.rate_limit_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.network.rate_limit.v2.RateLimit)
  ))
_sym_db.RegisterMessage(RateLimit)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7io.envoyproxy.envoy.config.filter.network.rate_limit.v2B\016RateLimitProtoP\001Z\002v2'))
_RATELIMIT.fields_by_name['stat_prefix'].has_options = True
_RATELIMIT.fields_by_name['stat_prefix']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_RATELIMIT.fields_by_name['domain'].has_options = True
_RATELIMIT.fields_by_name['domain']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_RATELIMIT.fields_by_name['descriptors'].has_options = True
_RATELIMIT.fields_by_name['descriptors']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\222\001\002\010\001'))
_RATELIMIT.fields_by_name['timeout'].has_options = True
_RATELIMIT.fields_by_name['timeout']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\230\337\037\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
