# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from envoy.api.v2 import discovery_pb2 as envoy_dot_api_dot_v2_dot_discovery__pb2


class ClusterDiscoveryServiceStub(object):
  """Return list of all clusters this proxy will load balance to.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StreamClusters = channel.stream_stream(
        '/envoy.api.v2.ClusterDiscoveryService/StreamClusters',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.FromString,
        )
    self.DeltaClusters = channel.stream_stream(
        '/envoy.api.v2.ClusterDiscoveryService/DeltaClusters',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DeltaDiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DeltaDiscoveryResponse.FromString,
        )
    self.FetchClusters = channel.unary_unary(
        '/envoy.api.v2.ClusterDiscoveryService/FetchClusters',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.FromString,
        )


class ClusterDiscoveryServiceServicer(object):
  """Return list of all clusters this proxy will load balance to.
  """

  def StreamClusters(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeltaClusters(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchClusters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClusterDiscoveryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StreamClusters': grpc.stream_stream_rpc_method_handler(
          servicer.StreamClusters,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.SerializeToString,
      ),
      'DeltaClusters': grpc.stream_stream_rpc_method_handler(
          servicer.DeltaClusters,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DeltaDiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DeltaDiscoveryResponse.SerializeToString,
      ),
      'FetchClusters': grpc.unary_unary_rpc_method_handler(
          servicer.FetchClusters,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'envoy.api.v2.ClusterDiscoveryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
