# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from envoy.api.v2 import discovery_pb2 as envoy_dot_api_dot_v2_dot_discovery__pb2


class EndpointDiscoveryServiceStub(object):
  """[#protodoc-title: EDS]

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StreamEndpoints = channel.stream_stream(
        '/envoy.api.v2.EndpointDiscoveryService/StreamEndpoints',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.FromString,
        )
    self.FetchEndpoints = channel.unary_unary(
        '/envoy.api.v2.EndpointDiscoveryService/FetchEndpoints',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.FromString,
        )


class EndpointDiscoveryServiceServicer(object):
  """[#protodoc-title: EDS]

  """

  def StreamEndpoints(self, request_iterator, context):
    """The resource_names field in DiscoveryRequest specifies a list of clusters
    to subscribe to updates for.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchEndpoints(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EndpointDiscoveryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StreamEndpoints': grpc.stream_stream_rpc_method_handler(
          servicer.StreamEndpoints,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.SerializeToString,
      ),
      'FetchEndpoints': grpc.unary_unary_rpc_method_handler(
          servicer.FetchEndpoints,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'envoy.api.v2.EndpointDiscoveryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
