# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from envoy.api.v2 import discovery_pb2 as envoy_dot_api_dot_v2_dot_discovery__pb2


class ListenerDiscoveryServiceStub(object):
  """[#protodoc-title: Listener]
  Listener :ref:`configuration overview <config_listeners>`

  The Envoy instance initiates an RPC at startup to discover a list of
  listeners. Updates are delivered via streaming from the LDS server and
  consist of a complete update of all listeners. Existing connections will be
  allowed to drain from listeners that are no longer present.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StreamListeners = channel.stream_stream(
        '/envoy.api.v2.ListenerDiscoveryService/StreamListeners',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.FromString,
        )
    self.FetchListeners = channel.unary_unary(
        '/envoy.api.v2.ListenerDiscoveryService/FetchListeners',
        request_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.SerializeToString,
        response_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.FromString,
        )


class ListenerDiscoveryServiceServicer(object):
  """[#protodoc-title: Listener]
  Listener :ref:`configuration overview <config_listeners>`

  The Envoy instance initiates an RPC at startup to discover a list of
  listeners. Updates are delivered via streaming from the LDS server and
  consist of a complete update of all listeners. Existing connections will be
  allowed to drain from listeners that are no longer present.
  """

  def StreamListeners(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchListeners(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ListenerDiscoveryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StreamListeners': grpc.stream_stream_rpc_method_handler(
          servicer.StreamListeners,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.SerializeToString,
      ),
      'FetchListeners': grpc.unary_unary_rpc_method_handler(
          servicer.FetchListeners,
          request_deserializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryRequest.FromString,
          response_serializer=envoy_dot_api_dot_v2_dot_discovery__pb2.DiscoveryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'envoy.api.v2.ListenerDiscoveryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
