# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/network/mysql_proxy/v1alpha1/mysql_proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/network/mysql_proxy/v1alpha1/mysql_proxy.proto',
  package='envoy.config.filter.network.mysql_proxy.v1alpha1',
  syntax='proto3',
  serialized_pb=_b('\nBenvoy/config/filter/network/mysql_proxy/v1alpha1/mysql_proxy.proto\x12\x30\x65nvoy.config.filter.network.mysql_proxy.v1alpha1\x1a\x17validate/validate.proto\"@\n\nMySQLProxy\x12\x1e\n\x0bstat_prefix\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\x12\n\naccess_log\x18\x02 \x01(\tB]\n>io.envoyproxy.envoy.config.filter.network.mysql_proxy.v1alpha1B\x0fMysqlProxyProtoP\x01Z\x08v1alpha1b\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,])




_MYSQLPROXY = _descriptor.Descriptor(
  name='MySQLProxy',
  full_name='envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat_prefix', full_name='envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProxy.stat_prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='access_log', full_name='envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProxy.access_log', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=209,
)

DESCRIPTOR.message_types_by_name['MySQLProxy'] = _MYSQLPROXY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MySQLProxy = _reflection.GeneratedProtocolMessageType('MySQLProxy', (_message.Message,), dict(
  DESCRIPTOR = _MYSQLPROXY,
  __module__ = 'envoy.config.filter.network.mysql_proxy.v1alpha1.mysql_proxy_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProxy)
  ))
_sym_db.RegisterMessage(MySQLProxy)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n>io.envoyproxy.envoy.config.filter.network.mysql_proxy.v1alpha1B\017MysqlProxyProtoP\001Z\010v1alpha1'))
_MYSQLPROXY.fields_by_name['stat_prefix'].has_options = True
_MYSQLPROXY.fields_by_name['stat_prefix']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
