# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/api/v2/ratelimit/ratelimit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/api/v2/ratelimit/ratelimit.proto',
  package='envoy.api.v2.ratelimit',
  syntax='proto3',
  serialized_pb=_b('\n&envoy/api/v2/ratelimit/ratelimit.proto\x12\x16\x65nvoy.api.v2.ratelimit\x1a\x17validate/validate.proto\"\xa0\x01\n\x13RateLimitDescriptor\x12N\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x31.envoy.api.v2.ratelimit.RateLimitDescriptor.EntryB\n\xba\xe9\xc0\x03\x05\x92\x01\x02\x08\x01\x1a\x39\n\x05\x45ntry\x12\x16\n\x03key\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\x18\n\x05value\x18\x02 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x42\x43\n$io.envoyproxy.envoy.api.v2.ratelimitB\x0eRatelimitProtoP\x01Z\tratelimitb\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,])




_RATELIMITDESCRIPTOR_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='envoy.api.v2.ratelimit.RateLimitDescriptor.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='envoy.api.v2.ratelimit.RateLimitDescriptor.Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='value', full_name='envoy.api.v2.ratelimit.RateLimitDescriptor.Entry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=252,
)

_RATELIMITDESCRIPTOR = _descriptor.Descriptor(
  name='RateLimitDescriptor',
  full_name='envoy.api.v2.ratelimit.RateLimitDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='envoy.api.v2.ratelimit.RateLimitDescriptor.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\222\001\002\010\001'))),
  ],
  extensions=[
  ],
  nested_types=[_RATELIMITDESCRIPTOR_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=252,
)

_RATELIMITDESCRIPTOR_ENTRY.containing_type = _RATELIMITDESCRIPTOR
_RATELIMITDESCRIPTOR.fields_by_name['entries'].message_type = _RATELIMITDESCRIPTOR_ENTRY
DESCRIPTOR.message_types_by_name['RateLimitDescriptor'] = _RATELIMITDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RateLimitDescriptor = _reflection.GeneratedProtocolMessageType('RateLimitDescriptor', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _RATELIMITDESCRIPTOR_ENTRY,
    __module__ = 'envoy.api.v2.ratelimit.ratelimit_pb2'
    # @@protoc_insertion_point(class_scope:envoy.api.v2.ratelimit.RateLimitDescriptor.Entry)
    ))
  ,
  DESCRIPTOR = _RATELIMITDESCRIPTOR,
  __module__ = 'envoy.api.v2.ratelimit.ratelimit_pb2'
  # @@protoc_insertion_point(class_scope:envoy.api.v2.ratelimit.RateLimitDescriptor)
  ))
_sym_db.RegisterMessage(RateLimitDescriptor)
_sym_db.RegisterMessage(RateLimitDescriptor.Entry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$io.envoyproxy.envoy.api.v2.ratelimitB\016RatelimitProtoP\001Z\tratelimit'))
_RATELIMITDESCRIPTOR_ENTRY.fields_by_name['key'].has_options = True
_RATELIMITDESCRIPTOR_ENTRY.fields_by_name['key']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_RATELIMITDESCRIPTOR_ENTRY.fields_by_name['value'].has_options = True
_RATELIMITDESCRIPTOR_ENTRY.fields_by_name['value']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_RATELIMITDESCRIPTOR.fields_by_name['entries'].has_options = True
_RATELIMITDESCRIPTOR.fields_by_name['entries']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\222\001\002\010\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
