# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/http/fault/v2/fault.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.api.v2.route import route_pb2 as envoy_dot_api_dot_v2_dot_route_dot_route__pb2
from envoy.config.filter.fault.v2 import fault_pb2 as envoy_dot_config_dot_filter_dot_fault_dot_v2_dot_fault__pb2
from envoy.type import percent_pb2 as envoy_dot_type_dot_percent__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/http/fault/v2/fault.proto',
  package='envoy.config.filter.http.fault.v2',
  syntax='proto3',
  serialized_pb=_b('\n-envoy/config/filter/http/fault/v2/fault.proto\x12!envoy.config.filter.http.fault.v2\x1a\x1e\x65nvoy/api/v2/route/route.proto\x1a(envoy/config/filter/fault/v2/fault.proto\x1a\x18\x65nvoy/type/percent.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\"\x80\x01\n\nFaultAbort\x12$\n\x0bhttp_status\x18\x02 \x01(\rB\r\xba\xe9\xc0\x03\x08*\x06\x10\xd8\x04(\xc8\x01H\x00\x12\x31\n\npercentage\x18\x03 \x01(\x0b\x32\x1d.envoy.type.FractionalPercentB\x13\n\nerror_type\x12\x05\xb8\xe9\xc0\x03\x01J\x04\x08\x01\x10\x02\"\xa3\x02\n\tHTTPFault\x12\x37\n\x05\x64\x65lay\x18\x01 \x01(\x0b\x32(.envoy.config.filter.fault.v2.FaultDelay\x12<\n\x05\x61\x62ort\x18\x02 \x01(\x0b\x32-.envoy.config.filter.http.fault.v2.FaultAbort\x12\x18\n\x10upstream_cluster\x18\x03 \x01(\t\x12\x32\n\x07headers\x18\x04 \x03(\x0b\x32!.envoy.api.v2.route.HeaderMatcher\x12\x18\n\x10\x64ownstream_nodes\x18\x05 \x03(\t\x12\x37\n\x11max_active_faults\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueBC\n/io.envoyproxy.envoy.config.filter.http.fault.v2B\nFaultProtoP\x01Z\x02v2b\x06proto3')
  ,
  dependencies=[envoy_dot_api_dot_v2_dot_route_dot_route__pb2.DESCRIPTOR,envoy_dot_config_dot_filter_dot_fault_dot_v2_dot_fault__pb2.DESCRIPTOR,envoy_dot_type_dot_percent__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,])




_FAULTABORT = _descriptor.Descriptor(
  name='FaultAbort',
  full_name='envoy.config.filter.http.fault.v2.FaultAbort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='http_status', full_name='envoy.config.filter.http.fault.v2.FaultAbort.http_status', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\010*\006\020\330\004(\310\001'))),
    _descriptor.FieldDescriptor(
      name='percentage', full_name='envoy.config.filter.http.fault.v2.FaultAbort.percentage', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='error_type', full_name='envoy.config.filter.http.fault.v2.FaultAbort.error_type',
      index=0, containing_type=None, fields=[], options=_descriptor._ParseOptions(descriptor_pb2.OneofOptions(), _b('\270\351\300\003\001'))),
  ],
  serialized_start=242,
  serialized_end=370,
)


_HTTPFAULT = _descriptor.Descriptor(
  name='HTTPFault',
  full_name='envoy.config.filter.http.fault.v2.HTTPFault',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay', full_name='envoy.config.filter.http.fault.v2.HTTPFault.delay', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abort', full_name='envoy.config.filter.http.fault.v2.HTTPFault.abort', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upstream_cluster', full_name='envoy.config.filter.http.fault.v2.HTTPFault.upstream_cluster', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headers', full_name='envoy.config.filter.http.fault.v2.HTTPFault.headers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='downstream_nodes', full_name='envoy.config.filter.http.fault.v2.HTTPFault.downstream_nodes', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_active_faults', full_name='envoy.config.filter.http.fault.v2.HTTPFault.max_active_faults', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=664,
)

_FAULTABORT.fields_by_name['percentage'].message_type = envoy_dot_type_dot_percent__pb2._FRACTIONALPERCENT
_FAULTABORT.oneofs_by_name['error_type'].fields.append(
  _FAULTABORT.fields_by_name['http_status'])
_FAULTABORT.fields_by_name['http_status'].containing_oneof = _FAULTABORT.oneofs_by_name['error_type']
_HTTPFAULT.fields_by_name['delay'].message_type = envoy_dot_config_dot_filter_dot_fault_dot_v2_dot_fault__pb2._FAULTDELAY
_HTTPFAULT.fields_by_name['abort'].message_type = _FAULTABORT
_HTTPFAULT.fields_by_name['headers'].message_type = envoy_dot_api_dot_v2_dot_route_dot_route__pb2._HEADERMATCHER
_HTTPFAULT.fields_by_name['max_active_faults'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['FaultAbort'] = _FAULTABORT
DESCRIPTOR.message_types_by_name['HTTPFault'] = _HTTPFAULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaultAbort = _reflection.GeneratedProtocolMessageType('FaultAbort', (_message.Message,), dict(
  DESCRIPTOR = _FAULTABORT,
  __module__ = 'envoy.config.filter.http.fault.v2.fault_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.http.fault.v2.FaultAbort)
  ))
_sym_db.RegisterMessage(FaultAbort)

HTTPFault = _reflection.GeneratedProtocolMessageType('HTTPFault', (_message.Message,), dict(
  DESCRIPTOR = _HTTPFAULT,
  __module__ = 'envoy.config.filter.http.fault.v2.fault_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.http.fault.v2.HTTPFault)
  ))
_sym_db.RegisterMessage(HTTPFault)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n/io.envoyproxy.envoy.config.filter.http.fault.v2B\nFaultProtoP\001Z\002v2'))
_FAULTABORT.oneofs_by_name['error_type'].has_options = True
_FAULTABORT.oneofs_by_name['error_type']._options = _descriptor._ParseOptions(descriptor_pb2.OneofOptions(), _b('\270\351\300\003\001'))
_FAULTABORT.fields_by_name['http_status'].has_options = True
_FAULTABORT.fields_by_name['http_status']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\010*\006\020\330\004(\310\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
