# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/http/ext_authz/v2alpha/ext_authz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.api.v2.core import grpc_service_pb2 as envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2
from envoy.api.v2.core import http_uri_pb2 as envoy_dot_api_dot_v2_dot_core_dot_http__uri__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/http/ext_authz/v2alpha/ext_authz.proto',
  package='envoy.config.filter.http.ext_authz.v2alpha',
  syntax='proto3',
  serialized_pb=_b('\n:envoy/config/filter/http/ext_authz/v2alpha/ext_authz.proto\x12*envoy.config.filter.http.ext_authz.v2alpha\x1a$envoy/api/v2/core/grpc_service.proto\x1a envoy/api/v2/core/http_uri.proto\"\xbb\x01\n\x08\x45xtAuthz\x12\x36\n\x0cgrpc_service\x18\x01 \x01(\x0b\x32\x1e.envoy.api.v2.core.GrpcServiceH\x00\x12O\n\x0chttp_service\x18\x03 \x01(\x0b\x32\x37.envoy.config.filter.http.ext_authz.v2alpha.HttpServiceH\x00\x12\x1a\n\x12\x66\x61ilure_mode_allow\x18\x02 \x01(\x08\x42\n\n\x08services\"v\n\x0bHttpService\x12.\n\nserver_uri\x18\x01 \x01(\x0b\x32\x1a.envoy.api.v2.core.HttpUri\x12\x13\n\x0bpath_prefix\x18\x02 \x01(\t\x12\"\n\x1aresponse_headers_to_remove\x18\x03 \x03(\tB\tZ\x07v2alphab\x06proto3')
  ,
  dependencies=[envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2.DESCRIPTOR,envoy_dot_api_dot_v2_dot_core_dot_http__uri__pb2.DESCRIPTOR,])




_EXTAUTHZ = _descriptor.Descriptor(
  name='ExtAuthz',
  full_name='envoy.config.filter.http.ext_authz.v2alpha.ExtAuthz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grpc_service', full_name='envoy.config.filter.http.ext_authz.v2alpha.ExtAuthz.grpc_service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='http_service', full_name='envoy.config.filter.http.ext_authz.v2alpha.ExtAuthz.http_service', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_mode_allow', full_name='envoy.config.filter.http.ext_authz.v2alpha.ExtAuthz.failure_mode_allow', index=2,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='services', full_name='envoy.config.filter.http.ext_authz.v2alpha.ExtAuthz.services',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=179,
  serialized_end=366,
)


_HTTPSERVICE = _descriptor.Descriptor(
  name='HttpService',
  full_name='envoy.config.filter.http.ext_authz.v2alpha.HttpService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_uri', full_name='envoy.config.filter.http.ext_authz.v2alpha.HttpService.server_uri', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_prefix', full_name='envoy.config.filter.http.ext_authz.v2alpha.HttpService.path_prefix', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_headers_to_remove', full_name='envoy.config.filter.http.ext_authz.v2alpha.HttpService.response_headers_to_remove', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=486,
)

_EXTAUTHZ.fields_by_name['grpc_service'].message_type = envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2._GRPCSERVICE
_EXTAUTHZ.fields_by_name['http_service'].message_type = _HTTPSERVICE
_EXTAUTHZ.oneofs_by_name['services'].fields.append(
  _EXTAUTHZ.fields_by_name['grpc_service'])
_EXTAUTHZ.fields_by_name['grpc_service'].containing_oneof = _EXTAUTHZ.oneofs_by_name['services']
_EXTAUTHZ.oneofs_by_name['services'].fields.append(
  _EXTAUTHZ.fields_by_name['http_service'])
_EXTAUTHZ.fields_by_name['http_service'].containing_oneof = _EXTAUTHZ.oneofs_by_name['services']
_HTTPSERVICE.fields_by_name['server_uri'].message_type = envoy_dot_api_dot_v2_dot_core_dot_http__uri__pb2._HTTPURI
DESCRIPTOR.message_types_by_name['ExtAuthz'] = _EXTAUTHZ
DESCRIPTOR.message_types_by_name['HttpService'] = _HTTPSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtAuthz = _reflection.GeneratedProtocolMessageType('ExtAuthz', (_message.Message,), dict(
  DESCRIPTOR = _EXTAUTHZ,
  __module__ = 'envoy.config.filter.http.ext_authz.v2alpha.ext_authz_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.http.ext_authz.v2alpha.ExtAuthz)
  ))
_sym_db.RegisterMessage(ExtAuthz)

HttpService = _reflection.GeneratedProtocolMessageType('HttpService', (_message.Message,), dict(
  DESCRIPTOR = _HTTPSERVICE,
  __module__ = 'envoy.config.filter.http.ext_authz.v2alpha.ext_authz_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.http.ext_authz.v2alpha.HttpService)
  ))
_sym_db.RegisterMessage(HttpService)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\007v2alpha'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
