# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.config.filter.network.dubbo_proxy.v2alpha1 import route_pb2 as envoy_dot_config_dot_filter_dot_network_dot_dubbo__proxy_dot_v2alpha1_dot_route__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from validate import validate_pb2 as validate_dot_validate__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto',
  package='envoy.config.filter.network.dubbo_proxy.v2alpha1',
  syntax='proto3',
  serialized_pb=_b('\nBenvoy/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto\x12\x30\x65nvoy.config.filter.network.dubbo_proxy.v2alpha1\x1a<envoy/config/filter/network/dubbo_proxy/v2alpha1/route.proto\x1a\x19google/protobuf/any.proto\x1a\x17validate/validate.proto\x1a\x14gogoproto/gogo.proto\"\xae\x03\n\nDubboProxy\x12\x1e\n\x0bstat_prefix\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\x61\n\rprotocol_type\x18\x02 \x01(\x0e\x32>.envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolTypeB\n\xba\xe9\xc0\x03\x05\x82\x01\x02\x10\x01\x12k\n\x12serialization_type\x18\x03 \x01(\x0e\x32\x43.envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationTypeB\n\xba\xe9\xc0\x03\x05\x82\x01\x02\x10\x01\x12Z\n\x0croute_config\x18\x04 \x03(\x0b\x32\x44.envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration\x12T\n\rdubbo_filters\x18\x05 \x03(\x0b\x32=.envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter\"L\n\x0b\x44ubboFilter\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12$\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any*\x19\n\x0cProtocolType\x12\t\n\x05\x44ubbo\x10\x00*!\n\x11SerializationType\x12\x0c\n\x08Hessian2\x10\x00\x42W\n>io.envoyproxy.envoy.config.filter.network.dubbo_proxy.v2alpha1B\x0f\x44ubboProxyProtoP\x01Z\x02v2b\x06proto3')
  ,
  dependencies=[envoy_dot_config_dot_filter_dot_network_dot_dubbo__proxy_dot_v2alpha1_dot_route__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])

_PROTOCOLTYPE = _descriptor.EnumDescriptor(
  name='ProtocolType',
  full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Dubbo', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=767,
  serialized_end=792,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOLTYPE)

ProtocolType = enum_type_wrapper.EnumTypeWrapper(_PROTOCOLTYPE)
_SERIALIZATIONTYPE = _descriptor.EnumDescriptor(
  name='SerializationType',
  full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Hessian2', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=794,
  serialized_end=827,
)
_sym_db.RegisterEnumDescriptor(_SERIALIZATIONTYPE)

SerializationType = enum_type_wrapper.EnumTypeWrapper(_SERIALIZATIONTYPE)
Dubbo = 0
Hessian2 = 0



_DUBBOPROXY = _descriptor.Descriptor(
  name='DubboProxy',
  full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat_prefix', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.stat_prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='protocol_type', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.protocol_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\202\001\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='serialization_type', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.serialization_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\202\001\002\020\001'))),
    _descriptor.FieldDescriptor(
      name='route_config', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.route_config', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dubbo_filters', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.dubbo_filters', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=687,
)


_DUBBOFILTER = _descriptor.Descriptor(
  name='DubboFilter',
  full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='config', full_name='envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=765,
)

_DUBBOPROXY.fields_by_name['protocol_type'].enum_type = _PROTOCOLTYPE
_DUBBOPROXY.fields_by_name['serialization_type'].enum_type = _SERIALIZATIONTYPE
_DUBBOPROXY.fields_by_name['route_config'].message_type = envoy_dot_config_dot_filter_dot_network_dot_dubbo__proxy_dot_v2alpha1_dot_route__pb2._ROUTECONFIGURATION
_DUBBOPROXY.fields_by_name['dubbo_filters'].message_type = _DUBBOFILTER
_DUBBOFILTER.fields_by_name['config'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['DubboProxy'] = _DUBBOPROXY
DESCRIPTOR.message_types_by_name['DubboFilter'] = _DUBBOFILTER
DESCRIPTOR.enum_types_by_name['ProtocolType'] = _PROTOCOLTYPE
DESCRIPTOR.enum_types_by_name['SerializationType'] = _SERIALIZATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DubboProxy = _reflection.GeneratedProtocolMessageType('DubboProxy', (_message.Message,), dict(
  DESCRIPTOR = _DUBBOPROXY,
  __module__ = 'envoy.config.filter.network.dubbo_proxy.v2alpha1.dubbo_proxy_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy)
  ))
_sym_db.RegisterMessage(DubboProxy)

DubboFilter = _reflection.GeneratedProtocolMessageType('DubboFilter', (_message.Message,), dict(
  DESCRIPTOR = _DUBBOFILTER,
  __module__ = 'envoy.config.filter.network.dubbo_proxy.v2alpha1.dubbo_proxy_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter)
  ))
_sym_db.RegisterMessage(DubboFilter)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n>io.envoyproxy.envoy.config.filter.network.dubbo_proxy.v2alpha1B\017DubboProxyProtoP\001Z\002v2'))
_DUBBOPROXY.fields_by_name['stat_prefix'].has_options = True
_DUBBOPROXY.fields_by_name['stat_prefix']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_DUBBOPROXY.fields_by_name['protocol_type'].has_options = True
_DUBBOPROXY.fields_by_name['protocol_type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\202\001\002\020\001'))
_DUBBOPROXY.fields_by_name['serialization_type'].has_options = True
_DUBBOPROXY.fields_by_name['serialization_type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\202\001\002\020\001'))
_DUBBOFILTER.fields_by_name['name'].has_options = True
_DUBBOFILTER.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
