# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/extensions/filters/network/thrift_proxy/v2alpha1/thrift_proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/extensions/filters/network/thrift_proxy/v2alpha1/thrift_proxy.proto',
  package='envoy.extensions.filters.network.thrift_proxy.v2alpha1',
  syntax='proto3',
  serialized_pb=_b('\nIenvoy/extensions/filters/network/thrift_proxy/v2alpha1/thrift_proxy.proto\x12\x36\x65nvoy.extensions.filters.network.thrift_proxy.v2alpha1\x1a\x17validate/validate.proto\"-\n\x0bThriftProxy\x12\x1e\n\x0bstat_prefix\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x42\x04Z\x02v2b\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,])




_THRIFTPROXY = _descriptor.Descriptor(
  name='ThriftProxy',
  full_name='envoy.extensions.filters.network.thrift_proxy.v2alpha1.ThriftProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat_prefix', full_name='envoy.extensions.filters.network.thrift_proxy.v2alpha1.ThriftProxy.stat_prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['ThriftProxy'] = _THRIFTPROXY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThriftProxy = _reflection.GeneratedProtocolMessageType('ThriftProxy', (_message.Message,), dict(
  DESCRIPTOR = _THRIFTPROXY,
  __module__ = 'envoy.extensions.filters.network.thrift_proxy.v2alpha1.thrift_proxy_pb2'
  # @@protoc_insertion_point(class_scope:envoy.extensions.filters.network.thrift_proxy.v2alpha1.ThriftProxy)
  ))
_sym_db.RegisterMessage(ThriftProxy)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\002v2'))
_THRIFTPROXY.fields_by_name['stat_prefix'].has_options = True
_THRIFTPROXY.fields_by_name['stat_prefix']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
