# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/filter/listener/original_src/v2alpha1/original_src.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/filter/listener/original_src/v2alpha1/original_src.proto',
  package='envoy.config.filter.listener.original_src.v2alpha1',
  syntax='proto3',
  serialized_pb=_b('\nEenvoy/config/filter/listener/original_src/v2alpha1/original_src.proto\x12\x32\x65nvoy.config.filter.listener.original_src.v2alpha1\x1a\x17validate/validate.proto\".\n\x0bOriginalSrc\x12\x11\n\tbind_port\x18\x01 \x01(\x08\x12\x0c\n\x04mark\x18\x02 \x01(\rB`\n@io.envoyproxy.envoy.config.filter.listener.original_src.v2alpha1B\x10OriginalSrcProtoP\x01Z\x08v2alpha1b\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,])




_ORIGINALSRC = _descriptor.Descriptor(
  name='OriginalSrc',
  full_name='envoy.config.filter.listener.original_src.v2alpha1.OriginalSrc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bind_port', full_name='envoy.config.filter.listener.original_src.v2alpha1.OriginalSrc.bind_port', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mark', full_name='envoy.config.filter.listener.original_src.v2alpha1.OriginalSrc.mark', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['OriginalSrc'] = _ORIGINALSRC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OriginalSrc = _reflection.GeneratedProtocolMessageType('OriginalSrc', (_message.Message,), dict(
  DESCRIPTOR = _ORIGINALSRC,
  __module__ = 'envoy.config.filter.listener.original_src.v2alpha1.original_src_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.filter.listener.original_src.v2alpha1.OriginalSrc)
  ))
_sym_db.RegisterMessage(OriginalSrc)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@io.envoyproxy.envoy.config.filter.listener.original_src.v2alpha1B\020OriginalSrcProtoP\001Z\010v2alpha1'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
