# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/resource_monitor/fixed_heap/v2alpha/fixed_heap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/resource_monitor/fixed_heap/v2alpha/fixed_heap.proto',
  package='envoy.config.resource_monitor.fixed_heap.v2alpha',
  syntax='proto3',
  serialized_pb=_b('\nAenvoy/config/resource_monitor/fixed_heap/v2alpha/fixed_heap.proto\x12\x30\x65nvoy.config.resource_monitor.fixed_heap.v2alpha\".\n\x0f\x46ixedHeapConfig\x12\x1b\n\x13max_heap_size_bytes\x18\x01 \x01(\x04\x42[\n>io.envoyproxy.envoy.config.resource_monitor.fixed_heap.v2alphaB\x0e\x46ixedHeapProtoP\x01Z\x07v2alphab\x06proto3')
)




_FIXEDHEAPCONFIG = _descriptor.Descriptor(
  name='FixedHeapConfig',
  full_name='envoy.config.resource_monitor.fixed_heap.v2alpha.FixedHeapConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_heap_size_bytes', full_name='envoy.config.resource_monitor.fixed_heap.v2alpha.FixedHeapConfig.max_heap_size_bytes', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['FixedHeapConfig'] = _FIXEDHEAPCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FixedHeapConfig = _reflection.GeneratedProtocolMessageType('FixedHeapConfig', (_message.Message,), dict(
  DESCRIPTOR = _FIXEDHEAPCONFIG,
  __module__ = 'envoy.config.resource_monitor.fixed_heap.v2alpha.fixed_heap_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.resource_monitor.fixed_heap.v2alpha.FixedHeapConfig)
  ))
_sym_db.RegisterMessage(FixedHeapConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n>io.envoyproxy.envoy.config.resource_monitor.fixed_heap.v2alphaB\016FixedHeapProtoP\001Z\007v2alpha'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
