# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/metrics/v2/metrics_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.api.v2.core import grpc_service_pb2 as envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/metrics/v2/metrics_service.proto',
  package='envoy.config.metrics.v2',
  syntax='proto3',
  serialized_pb=_b('\n-envoy/config/metrics/v2/metrics_service.proto\x12\x17\x65nvoy.config.metrics.v2\x1a$envoy/api/v2/core/grpc_service.proto\x1a\x17validate/validate.proto\"X\n\x14MetricsServiceConfig\x12@\n\x0cgrpc_service\x18\x01 \x01(\x0b\x32\x1e.envoy.api.v2.core.GrpcServiceB\n\xba\xe9\xc0\x03\x05\x8a\x01\x02\x10\x01\x62\x06proto3')
  ,
  dependencies=[envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,])




_METRICSSERVICECONFIG = _descriptor.Descriptor(
  name='MetricsServiceConfig',
  full_name='envoy.config.metrics.v2.MetricsServiceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grpc_service', full_name='envoy.config.metrics.v2.MetricsServiceConfig.grpc_service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\212\001\002\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=225,
)

_METRICSSERVICECONFIG.fields_by_name['grpc_service'].message_type = envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2._GRPCSERVICE
DESCRIPTOR.message_types_by_name['MetricsServiceConfig'] = _METRICSSERVICECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricsServiceConfig = _reflection.GeneratedProtocolMessageType('MetricsServiceConfig', (_message.Message,), dict(
  DESCRIPTOR = _METRICSSERVICECONFIG,
  __module__ = 'envoy.config.metrics.v2.metrics_service_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.metrics.v2.MetricsServiceConfig)
  ))
_sym_db.RegisterMessage(MetricsServiceConfig)


_METRICSSERVICECONFIG.fields_by_name['grpc_service'].has_options = True
_METRICSSERVICECONFIG.fields_by_name['grpc_service']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\212\001\002\020\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
