# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/accesslog/v2/file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/accesslog/v2/file.proto',
  package='envoy.config.accesslog.v2',
  syntax='proto3',
  serialized_pb=_b('\n$envoy/config/accesslog/v2/file.proto\x12\x19\x65nvoy.config.accesslog.v2\x1a\x17validate/validate.proto\"8\n\rFileAccessLog\x12\x17\n\x04path\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\tB\x04Z\x02v2b\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,])




_FILEACCESSLOG = _descriptor.Descriptor(
  name='FileAccessLog',
  full_name='envoy.config.accesslog.v2.FileAccessLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='envoy.config.accesslog.v2.FileAccessLog.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='format', full_name='envoy.config.accesslog.v2.FileAccessLog.format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['FileAccessLog'] = _FILEACCESSLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileAccessLog = _reflection.GeneratedProtocolMessageType('FileAccessLog', (_message.Message,), dict(
  DESCRIPTOR = _FILEACCESSLOG,
  __module__ = 'envoy.config.accesslog.v2.file_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.accesslog.v2.FileAccessLog)
  ))
_sym_db.RegisterMessage(FileAccessLog)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\002v2'))
_FILEACCESSLOG.fields_by_name['path'].has_options = True
_FILEACCESSLOG.fields_by_name['path']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
