# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/trace/v2/trace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.api.v2.core import grpc_service_pb2 as envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy/config/trace/v2/trace.proto',
  package='envoy.config.trace.v2',
  syntax='proto3',
  serialized_pb=_b('\n!envoy/config/trace/v2/trace.proto\x12\x15\x65nvoy.config.trace.v2\x1a$envoy/api/v2/core/grpc_service.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"\x86\x01\n\x07Tracing\x12\x31\n\x04http\x18\x01 \x01(\x0b\x32#.envoy.config.trace.v2.Tracing.Http\x1aH\n\x04Http\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\'\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"]\n\x0fLightstepConfig\x12$\n\x11\x63ollector_cluster\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12$\n\x11\x61\x63\x63\x65ss_token_file\x18\x02 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\"t\n\x0cZipkinConfig\x12$\n\x11\x63ollector_cluster\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12%\n\x12\x63ollector_endpoint\x18\x02 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\x17\n\x0ftrace_id_128bit\x18\x03 \x01(\x08\"V\n\x0f\x44ynamicOtConfig\x12\x1a\n\x07library\x18\x01 \x01(\tB\t\xba\xe9\xc0\x03\x04r\x02 \x01\x12\'\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"V\n\x12TraceServiceConfig\x12@\n\x0cgrpc_service\x18\x01 \x01(\x0b\x32\x1e.envoy.api.v2.core.GrpcServiceB\n\xba\xe9\xc0\x03\x05\x8a\x01\x02\x10\x01\x42\x04Z\x02v2b\x06proto3')
  ,
  dependencies=[envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,])




_TRACING_HTTP = _descriptor.Descriptor(
  name='Http',
  full_name='envoy.config.trace.v2.Tracing.Http',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='envoy.config.trace.v2.Tracing.Http.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='config', full_name='envoy.config.trace.v2.Tracing.Http.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=288,
)

_TRACING = _descriptor.Descriptor(
  name='Tracing',
  full_name='envoy.config.trace.v2.Tracing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='http', full_name='envoy.config.trace.v2.Tracing.http', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRACING_HTTP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=288,
)


_LIGHTSTEPCONFIG = _descriptor.Descriptor(
  name='LightstepConfig',
  full_name='envoy.config.trace.v2.LightstepConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collector_cluster', full_name='envoy.config.trace.v2.LightstepConfig.collector_cluster', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='access_token_file', full_name='envoy.config.trace.v2.LightstepConfig.access_token_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=383,
)


_ZIPKINCONFIG = _descriptor.Descriptor(
  name='ZipkinConfig',
  full_name='envoy.config.trace.v2.ZipkinConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collector_cluster', full_name='envoy.config.trace.v2.ZipkinConfig.collector_cluster', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='collector_endpoint', full_name='envoy.config.trace.v2.ZipkinConfig.collector_endpoint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='trace_id_128bit', full_name='envoy.config.trace.v2.ZipkinConfig.trace_id_128bit', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=501,
)


_DYNAMICOTCONFIG = _descriptor.Descriptor(
  name='DynamicOtConfig',
  full_name='envoy.config.trace.v2.DynamicOtConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='library', full_name='envoy.config.trace.v2.DynamicOtConfig.library', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))),
    _descriptor.FieldDescriptor(
      name='config', full_name='envoy.config.trace.v2.DynamicOtConfig.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=589,
)


_TRACESERVICECONFIG = _descriptor.Descriptor(
  name='TraceServiceConfig',
  full_name='envoy.config.trace.v2.TraceServiceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grpc_service', full_name='envoy.config.trace.v2.TraceServiceConfig.grpc_service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\212\001\002\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=677,
)

_TRACING_HTTP.fields_by_name['config'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_TRACING_HTTP.containing_type = _TRACING
_TRACING.fields_by_name['http'].message_type = _TRACING_HTTP
_DYNAMICOTCONFIG.fields_by_name['config'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_TRACESERVICECONFIG.fields_by_name['grpc_service'].message_type = envoy_dot_api_dot_v2_dot_core_dot_grpc__service__pb2._GRPCSERVICE
DESCRIPTOR.message_types_by_name['Tracing'] = _TRACING
DESCRIPTOR.message_types_by_name['LightstepConfig'] = _LIGHTSTEPCONFIG
DESCRIPTOR.message_types_by_name['ZipkinConfig'] = _ZIPKINCONFIG
DESCRIPTOR.message_types_by_name['DynamicOtConfig'] = _DYNAMICOTCONFIG
DESCRIPTOR.message_types_by_name['TraceServiceConfig'] = _TRACESERVICECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tracing = _reflection.GeneratedProtocolMessageType('Tracing', (_message.Message,), dict(

  Http = _reflection.GeneratedProtocolMessageType('Http', (_message.Message,), dict(
    DESCRIPTOR = _TRACING_HTTP,
    __module__ = 'envoy.config.trace.v2.trace_pb2'
    # @@protoc_insertion_point(class_scope:envoy.config.trace.v2.Tracing.Http)
    ))
  ,
  DESCRIPTOR = _TRACING,
  __module__ = 'envoy.config.trace.v2.trace_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.trace.v2.Tracing)
  ))
_sym_db.RegisterMessage(Tracing)
_sym_db.RegisterMessage(Tracing.Http)

LightstepConfig = _reflection.GeneratedProtocolMessageType('LightstepConfig', (_message.Message,), dict(
  DESCRIPTOR = _LIGHTSTEPCONFIG,
  __module__ = 'envoy.config.trace.v2.trace_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.trace.v2.LightstepConfig)
  ))
_sym_db.RegisterMessage(LightstepConfig)

ZipkinConfig = _reflection.GeneratedProtocolMessageType('ZipkinConfig', (_message.Message,), dict(
  DESCRIPTOR = _ZIPKINCONFIG,
  __module__ = 'envoy.config.trace.v2.trace_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.trace.v2.ZipkinConfig)
  ))
_sym_db.RegisterMessage(ZipkinConfig)

DynamicOtConfig = _reflection.GeneratedProtocolMessageType('DynamicOtConfig', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICOTCONFIG,
  __module__ = 'envoy.config.trace.v2.trace_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.trace.v2.DynamicOtConfig)
  ))
_sym_db.RegisterMessage(DynamicOtConfig)

TraceServiceConfig = _reflection.GeneratedProtocolMessageType('TraceServiceConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRACESERVICECONFIG,
  __module__ = 'envoy.config.trace.v2.trace_pb2'
  # @@protoc_insertion_point(class_scope:envoy.config.trace.v2.TraceServiceConfig)
  ))
_sym_db.RegisterMessage(TraceServiceConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\002v2'))
_TRACING_HTTP.fields_by_name['name'].has_options = True
_TRACING_HTTP.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_LIGHTSTEPCONFIG.fields_by_name['collector_cluster'].has_options = True
_LIGHTSTEPCONFIG.fields_by_name['collector_cluster']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_LIGHTSTEPCONFIG.fields_by_name['access_token_file'].has_options = True
_LIGHTSTEPCONFIG.fields_by_name['access_token_file']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_ZIPKINCONFIG.fields_by_name['collector_cluster'].has_options = True
_ZIPKINCONFIG.fields_by_name['collector_cluster']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_ZIPKINCONFIG.fields_by_name['collector_endpoint'].has_options = True
_ZIPKINCONFIG.fields_by_name['collector_endpoint']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_DYNAMICOTCONFIG.fields_by_name['library'].has_options = True
_DYNAMICOTCONFIG.fields_by_name['library']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\004r\002 \001'))
_TRACESERVICECONFIG.fields_by_name['grpc_service'].has_options = True
_TRACESERVICECONFIG.fields_by_name['grpc_service']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\272\351\300\003\005\212\001\002\020\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
